### ISSUE TITLE
Relation to AutoFixture?

### ISSUE THREAD

**Issue by mkoertgen** [awesome-inc/NEdifis#1]
I stumbled upon the [PluralSight course on AutoFixture](http://www.pluralsight.com/courses/autofixture-dotnet-unit-test-get-started). How does NEdifis relate to [AutoFixture](https://github.com/AutoFixture/AutoFixture)

**Comment by ghost** [comment]
NEdifis is basically a collection of several classes for unit testing we use in our projects. The `ContextFor`is basically the mentioned SUT factory from AutoFixture (http://blog.ploeh.dk/2009/02/13/SUTFactory/).

NEdifis provide more like conventions and attributes for conventions. In addition the TraceListener support a test for tracing and debugging output.
